[package]
name = "hello-oracle-script"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owasm-kit = "0.1.13"
obi = "0.0.2"
